# Generated by Django 2.2 on 2021-06-27 04:29

from django.db import migrations, models
import stock_manage.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manage', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(upload_to=stock_manage.models.image_rename),
        ),
    ]
